
	<table>
		<theader>
			<th>Id</th>
			<th>Nombre</th>
			<th>Juego</th>
		</theader>
	<?php foreach($this->companies as $company){?>
		<tr>
			<td><?php echo $this->escape($company->id)?></td>
			<td><?php echo $this->escape($company->name)?></td>
			<td>
				<a href='<?php echo $this->url(array('controller'=>'game', 'action'=>'edit')) . "?game_id=".$company->game_id?>'>
					<?php echo $this->escape($this->games->getGameNameById($company->game_id))?>
				</a>
			</td>
			<td>
				<a href='<?php echo $this->url(array('controller'=>'company', 'action'=>'edit')) . "?company_id=".$company->id?>'>
					editar empresa
				</a>
			</td>
		</tr>
	<?php }//for  ?>
	</table>

