<div id="hrCostsEvolutionFieldDescription" class="fieldDescription"  style="background-color:white">
	Configure de forma porcentual (%) la evolución temporal de los costes de personal en cada ronda.
</div>
<?php $n_rounds=$view->games->getNumberOfRounds($view->game_id); ?>
	<?php if ($n_rounds>1) {?>
		<?php for ($round_number=2;$round_number<=$n_rounds;$round_number++){ ?>
			<div style="float: left; margin-right: 15px;">	
				Ronda <?php echo $round_number?>
				<table>
					<theader>
						<th class="small"></th>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
						<th class="small">Región <?php echo $region_number?></th>
						<?php } //for region?>
					</theader>
					<tr>
						<td></td>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
							<td class="inCellFieldHeader">Variación (%)</td>
						<?php } //for region?>
					</tr>
					<tr>
						<td>Contratación</td>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
						<td><input type="text" name="hrRegionCostsEvolution[round_<?php echo $round_number?>][region_<?php echo $region_number?>][hiring_evolution]" 
							value="<?php echo $view->games->getHrStaffCostEvolution($view->game_id, $round_number, $region_number, 'hiring_cost_evolution');?>"class="small"></td>
						<?php } //for region?>
					</tr>
					<tr>
						<td>Formación</td>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
						<td><input type="text" name="hrRegionCostsEvolution[round_<?php echo $round_number?>][region_<?php echo $region_number?>][training_evolution]" 
							value="<?php echo $view->games->getHrStaffCostEvolution($view->game_id, $round_number, $region_number, 'training_cost_evolution');?>" class="small"></td>
						<?php } //for region?>
					</tr>
					<tr>
						<td>Salarios</td>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
						<td><input type="text" name="hrRegionCostsEvolution[round_<?php echo $round_number?>][region_<?php echo $region_number?>][wages_evolution]" 
							value="<?php echo $view->games->getHrStaffCostEvolution($view->game_id, $round_number, $region_number, 'wages_cost_evolution');?>" class="small"></td>
						<?php } //for region?>
					</tr>
				</table>
			</div>
		<?php }?>
	<?php } else {?>
		<div style="float: left">	
			Sólo se ha configurado una ronda para este juego de simulación
		</div>
	<?php }?>
<div style="clear:both"></div>