<table>
	<theader>
		<th class="small">Producto</th>
		<th class="small">Canal</th>
		<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
		<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
			<th class="small">Región <?php echo $region_number?></th>
	<?php } //for region?>
	</theader>
	<tr>
		<td></td>
		<td></td>
		<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
		<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
			<td class="inCellFieldHeader">Precio Ideal : Precio Máx.</td>
		<?php } //for region?>
	</tr>
	<?php $n_products=$view->games->getNumberOfProducts($view->game_id); ?>
	<?php for ($product_number=1;$product_number<=$n_products;$product_number++){ ?>
		<?php $n_channels=$view->games->getNumberOfChannels($view->game_id); ?>
		<?php for ($channel_number=1;$channel_number<=$n_channels;$channel_number++){ ?>
	<tr>
			<td><?php if ($channel_number==round($n_channels/2)){echo "Producto ".$product_number;}?></td>
			<td>Canal <?php echo $channel_number?></td>
		<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
		<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
			<?php $marketPrices=$view->games->getMarketPrices($view->game_id, 1, $product_number, $channel_number, $region_number);?>
			<?php $maxPrice=$marketPrices['max_price'];?>
			<?php $idealPrice=$marketPrices['ideal_price'];?>
		<td>	
			<input type="text" name="marketProductPrices[round_1][product_<?php echo $product_number?>][channel_<?php echo $channel_number?>][region_<?php echo $region_number?>][idealPrice]" value="<?php echo $idealPrice?>" class="small">
			 : 
			<input type="text" name="marketProductPrices[round_1][product_<?php echo $product_number?>][channel_<?php echo $channel_number?>][region_<?php echo $region_number?>][maxPrice]" value="<?php echo $maxPrice?>" class="small">
		</td>
		<?php } //for region?>
	</tr>
		<?php } //for channel?>
	<?php } //for product?>
</table>