<div id="distrivutionCostsEvolutionFieldDescription" class="fieldDescription" style="background-color:white">
	Configure de forma porcentual (%) la evolución temporal de los costes de distribución en cada ronda.
</div>
<?php $n_rounds=$view->games->getNumberOfRounds($view->game_id); ?>
	<?php if ($n_rounds>1) {?>
		<?php for ($round_number=2;$round_number<=$n_rounds;$round_number++){ ?>
			<div style="float: left; margin-right: 15px;">
				Ronda <?php echo $round_number?>
				<table>
					<theader>
						<th class="small"></th>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
						<th class="small">Región <?php echo $region_number?></th>
						<?php } //for region?>
					</theader>
					<tr>
						<td></td>
						<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
							<td class="inCellFieldHeader">Variación (%)</td>
						<?php } //for region?>
					</tr>
					<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
						<?php for ($source_region_number=1;$source_region_number<=$n_regions;$source_region_number++){ ?>
						<tr>
							<td>Región <?php echo $source_region_number?></td>
							<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
							<?php for ($destination_region_number=1;$destination_region_number<=$n_regions;$destination_region_number++){ ?>
								<?php $costEvolution=$view->games->getDistributionCostEvolution($view->game_id, $round_number, $source_region_number, $destination_region_number);?>
								<td><input type="text" name="prDistributionCostsEvolution[round_<?php echo $round_number?>][region_<?php echo $source_region_number?>][region_<?php echo $destination_region_number?>]" class="small" value="<?php echo $costEvolution?>"></td>
							<?php } //for destination?>
						</tr>
					<?php }//for source ?>				
				</table>
			</div>
		<?php }?>
	<?php } else {?>
		<div style="float: left">
			Sólo se ha configurado una ronda para este juego de simulación
		</div>
	<?php }?>
<div style="clear:both"></div>