<div id="rawMaterialCostsEvolutionFieldDescription" class="fieldDescription" style="background-color:white">
	Configure de forma porcentual (%) la evolución temporal de los costes de abastecimiento en cada ronda.
</div>
<?php $n_rounds=$view->games->getNumberOfRounds($view->game_id); ?>
	<?php if ($n_rounds>1) {?>
		<?php for ($round_number=2;$round_number<=$n_rounds;$round_number++){ ?>
			<div style="float: left; margin-right: 15px;">
				Ronda <?php echo $round_number?>
				<table>
					<theader>
						<th class="small"></th>
						<?php $n_products=$view->games->getNumberOfProducts($view->game_id); ?>
						<?php for ($product_number=1;$product_number<=$n_products;$product_number++){ ?>
						<th class="small">Producto <?php echo $product_number?></th>
						<?php } //for product?>
					</theader>
					<tr>
						<td></td>
						<?php $n_products=$view->games->getNumberOfProducts($view->game_id); ?>
						<?php for ($product_number=1;$product_number<=$n_products;$product_number++){ ?>
							<td class="inCellFieldHeader">Variación (%)</td>
						<?php } ?>
					</tr>
					<tr>
						<td>Precio Base</td>
						<?php $n_products=$view->games->getNumberOfProducts($view->game_id); ?>
						<?php for ($product_number=1;$product_number<=$n_products;$product_number++){ ?>
							<?php $costEvolution=$view->games->getRawMaterialCostEvolution($view->game_id, $round_number, $product_number, 'evolution');?>
						<td><input type="text" name="prRawMaterialsCostsEvolution[round_<?php echo $round_number?>][product_<?php echo $product_number?>][evolution]" value="<?php echo $costEvolution?>" class="small"></td>
						<?php } //for product?>
					</tr>
				</table>
			</div>
		<?php }?>
	<?php } else {?>
		<div style="float: left">
			Sólo se ha configurado una ronda para este juego de simulación
		</div>
	<?php }?>
<div style="clear:both"></div>