<table>
	<theader>
		<th class="small"></th>
		<th class="small">Nombre</th>
	</theader>
	<?php $n_regions=$view->games->getNumberOfRegions($view->game_id); ?>
	<?php for ($region_number=1;$region_number<=$n_regions;$region_number++){ ?>
	<?php $region=$view->game_regions[$region_number-1]; ?>
	<tr>
		<td>Región <?php echo $region_number?></td>
		<td><input type="text" name="region_<?php echo $region_number?>[name]" class="medium" value="<?php echo $region['name']?>"></td>
	</tr>
	<?php } //foreach region?>
</table>