<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui/jquery-ui.css');?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery.min.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-ui.min.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-ui-i18n.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-1.9.1.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-ui-1.10.3.custom.min.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/ui.datepicker-es.js', $type = 'text/javascript')?>

<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/forms.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/editGame.css');?>

<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery.toastmessage.css');?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/jquery.toastmessage.js', $type = 'text/javascript')?>

<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/game_edit.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/generalScripts.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/game_config.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/validators/editgame.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/validators/validation.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/budget.js', $type = 'text/javascript')?>




<script src="http://malsup.github.com/jquery.form.js"></script>


<div id='content'>
	<?php if (isset($this->game)) { //si se ha definido un juego concreto?>
		<h1><?php echo $this->game['name']?> <a href="<?php echo $this->baseUrl()?>/game/">(volver a resumen)</a></h1>	
		<div id="formulario" style="border: none">

			<div id="menu_rondas">
				<ul>
					<li id="general-button"><a href="#general">General</a></li>
					<li id="parametros-button"><a href="#parametros">Parámetros</a></li>
					<li id="modulos-button"><a href="#modulos">Módulos</a></li>
				</ul>
			</div>

			<form id="formularioGeneral" name="game_config" method="post">
				<input type="text" style="display:none" value="dummy" name="formularioGral">
				<div id="general">
					<div id="general_tabs">
						<div id="menu_general">
							<ul>
								<li><a href="#descripcion">Descripción</a></li>
								<li><a href="#rondas">Rondas</a></li>
								<li><a href="#empresas">Empresas</a></li>
							</ul>
						</div>
						<div id="descripcion">
							<div id="descriptionField" class="fieldDiv">
								<div id="descriptionFieldDescription" class="fieldDescription">
									Introduzca una descripción que permita identificar el juego.
								</div>
								<textarea name="description" id="description" display="block"><?php echo $this->game['description']?></textarea>
							</div>
						</div>
						<div id="rondas">				
							<div id="roundsField" class="fieldDiv">
								<div id="roundsFieldDescription" class="fieldDescription">
									Introduzca la configuración de las rondas del juego.
								</div>
								<div id="roundsFieldsErrors" class="fieldErrors">
								</div>
								<input type="hidden" value="<?php echo $this->numberOfRounds?>" id="numberOfRounds" />
								<div id='roundsFieldsDiv'>
									<?php $roundCount=1;?>
									<?php foreach ($this->game_rounds as $round){?>
									<div id="roundField_<?php echo $roundCount?>" class="roundField">				
											<div class="roundHeader">
												Ronda <?php echo $roundCount?>.
											</div>
											<table>
												<tr>
													<td>
											Apertura
													</td>
													<td>
											<input type="text" id="round_<?php echo $roundCount?>_opening" name="round_<?php echo $roundCount?>_opening" class="date" value="<?php echo date('d/m/Y', strtotime($round['opening_date']))?>">
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_opening_hour" id="round_<?php echo $roundCount?>_opening_hour">
												<?php for ($h=23;$h>=0;$h--){?>
													<?php $hour=date('G', strtotime($round['opening_date']))?>
													<?php if ($h==$hour){?>
														<option selected value="<?php echo $h?>"><?php echo $h?></option>
													<?php } else {?>
														<option value="<?php echo $h?>"><?php echo $h?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_opening_minute" id="round_<?php echo $roundCount?>_opening_minute">
												<?php for ($m=59;$m>=0;$m--){?>
													<?php $minute=date('i', strtotime($round['opening_date']))?>
													<?php if ($m==$minute){?>
														<option selected value="<?php echo $m?>"><?php echo $m?></option>
													<?php } else {?>
														<option value="<?php echo $m?>"><?php echo $m?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_opening_second" id="round_<?php echo $roundCount?>_opening_second">
												<?php for ($s=59;$s>=0;$s--){?>
													<?php $second=date('s', strtotime($round['opening_date']))?>
													<?php if ($s==$second){?>
														<option selected value="<?php echo $s?>"><?php echo $s?></option>
													<?php } else {?>
														<option value="<?php echo $s?>"><?php echo $s?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
												</tr>
												<tr>
													<td>
											Cierre 
													</td>
													<td>
											<input type="text" id="round_<?php echo $roundCount?>_closing" name="round_<?php echo $roundCount?>_closing" class="date" value="<?php echo date('d/m/Y', strtotime($round['closing_date']))?>">
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_closing_hour" id="round_<?php echo $roundCount?>_closing_hour">
												<?php for ($h=23;$h>=0;$h--){?>
													<?php $hour=date('G', strtotime($round['closing_date']))?>
													<?php if ($h==$hour){?>
														<option selected value="<?php echo $h?>"><?php echo $h?></option>
													<?php } else {?>
														<option value="<?php echo $h?>"><?php echo $h?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_closing_minute" id="round_<?php echo $roundCount?>_closing_minute">
												<?php for ($m=59;$m>=0;$m--){?>
													<?php $minute=date('i', strtotime($round['closing_date']))?>
													<?php if ($m==$minute){?>
														<option selected value="<?php echo $m?>"><?php echo $m?></option>
													<?php } else {?>
														<option value="<?php echo $m?>"><?php echo $m?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
													<td>
											<select name="round_<?php echo $roundCount?>_closing_second" id="round_<?php echo $roundCount?>_closing_second">
												<?php for ($s=59;$s>=0;$s--){?>
													<?php $second=date('s', strtotime($round['closing_date']))?>
													<?php if ($s==$second){?>
														<option selected value="<?php echo $s?>"><?php echo $s?></option>
													<?php } else {?>
														<option value="<?php echo $s?>"><?php echo $s?></option>
													<?php } ?>
												<?php } ?>								
											</select>
													</td>
												</tr>
											</table>
											<br>
											<a href="" OnClick="deleteRound(<?php echo $roundCount?>);return false;">(X) eliminar</a>
									</div>
										<?php $roundCount++;?>
									<?php } ?>
								</div>
								<div class="fieldOptions">
									<a href="" OnClick="addRound();return false;">(+) añadir ronda.</a>
								</div>
							</div>
							<div class="buttonsDiv">
								<input class=button type="submit" value="Guardar Rondas">
							</div>
						</div>
						<div id="empresas">
							<?php if ($this->game['is_template']==0){?>
							<div id="companiesField" class="fieldDiv">
								<?php if (isset($this->companies) && count($this->companies)){?>
									<?php $this->gameTables($this, array("companies", $this->companies, $this))?>
								<?php } // if  
								else {?>
									<p>No hay empresas en el juego.</p>
								<?php }?>
								<div class="fieldOptions">		
									<a href='<?php echo $this->url(array('controller'=>'game', 'action'=>'addcompany'))."?game_id=".$this->game['id']?>'>(+) nueva empresa</a>
								</div>
							</div>
							<?php } //end if is_template?>
						</div>
					</div>
				</div>
			</form>	
			
			<form id="formularioParametros" name="game_config" method="post">
				<input type="text" style="display:none" value="dummy" name="formularioParam">
				<div id="parametros">
					<div id="parametersFields" class="fieldDiv">
						<div id="parametros_tabs">
							<div id="menu_parametros">
								<ul>
									<li><a href="#productos">Productos</a></li>
									<li><a href="#calidad">Calidad</a></li>
									<!--VERO -->
									<li><a href="#funcionalidades">Funcionalidades</a></li>
									<!--VERO -->
									<li><a href="#regiones">Regiones</a></li>
									<li><a href="#canales_distrib">Canales de distribución</a></li>
									<li><a href="#medios_publicitarios">Medios publicitarios</a></li>
									<li><a href="#iniciativas">Iniciativas</a></li>
									<li><a href="#mercados">Mercados</a></li>

								</ul>
							</div>
							<div id="productos">
								<div id="productsParametersFields">
									<div id="productsFieldDescription" class="fieldDescription">
										Configure los productos del juego. 
									</div>
									<div id="productsFieldsErrors" class="fieldErrors">
									</div>
									<div id="productsParametersContainer">
										<div id="productsFields"> 
										<?php $this->gameTables($this, "productsParameters")?>
										</div>
									</div>
								</div>
							</div>
							<div id="calidad">
								<div id="qualitiesParametersFields"> 
									<div id="qualitiesFieldDescription" class="fieldDescription">
										Configure los atributos de calidad y su peso en la calidad total para los productos del juego. 
									</div>
									<div id="qualitiesFieldsErrors" class="fieldErrors">
									</div>
									<div id="qualitiesParametersContainer">
										<div id="qualitiesFields">
										<?php $this->gameTables($this, "qualitiesParameters");?>
										</div>
									</div>
								</div>
							</div>
							<!--VERO -->
							<div id="funcionalidades">
								<div id="functionalityParametersFields"> 
									<div id="functionalityFieldDescription" class="fieldDescription">
										Configure los atributos de funcionalidades y su peso en la calidad total para los productos del juego. 
									</div>
									<div id="functionalityFieldsErrors" class="fieldErrors">
									</div>
									<div id="functionalityParametersContainer">
										<div id="functionalityFields">
										<?php $this->gameTables($this, "functionalityParameters");?>
										</div>
									</div>
								</div>
							</div>
							<!--VERO -->
							<div id="regiones">
								<div id="regionsParametersFields"> 
									<div id="regionsFieldDescription" class="fieldDescription">
										Configure las regiones del juego. 
									</div>
									<div id="regionsFieldsErrors" class="fieldErrors">
									</div>
									<div id="regionesContainer">
										<div id="regionsFields">
										<?php $this->gameTables($this, "regionsParameters");?>
										</div>
									</div>
								</div>
							</div>
							<div id="canales_distrib">
								<div id="channelsParametersFields"> 
									<div id="channelsFieldDescription" class="fieldDescription">
										Configure los canales de distribución disponibles para el juego y su importancia para el cómputo de Trade MKT. 
									</div>
									<div id="channelsFieldsErrors" class="fieldErrors">
									</div>
									<div id="channelsParametersContainer">
										
										<div id="channelsFields">
										<?php $this->gameTables($this, "channelsParameters");?>
										</div>
									</div>
								</div>
							</div>
							<div id="medios_publicitarios">
								<div id="mediaParametersFields"> 
									<div id="mediaFieldDescription" class="fieldDescription">
										Configure los medios disponibles para el juego y su importancia para el cómputo de Publicidad. 
									</div>
									<div id="mediaFieldsErrors" class="fieldErrors">
									</div>
									<div id="medios_publicitariosContainer">
										<div id="mediaFields">
										<?php $this->gameTables($this, "mediaParameters");?>
										</div>
									</div>
								</div>
							</div>
							<div id="iniciativas">
								<div id="initiativesParametersFields"> 
									<div id="initiativesFieldDescription" class="fieldDescription">
										Configure las iniciativas disponibles para el juego, las áreas funcionales de aplicación y cuantifique el impacto positivo que producirán. 
									</div>
									<div id="initiativesFieldsErrors" class="fieldErrors">
									</div>
									<div id="initiativesContainer">
										<div id="initiativesFields">
										<?php $this->gameTables($this, "initiativesParameters");?>
										</div>
									</div>
								</div>
							</div>
							<div id="mercados">
								<div id="marketsParametersFields">
									<div class="fieldCategory fieldDescription" id="marketSizesButton">
										1. Tamaño de mercados. <!-- Tamaño de mercados></!--> 
									</div>
									<div id="marketSizesFieldsErrors" class="fieldErrors">
									</div>
									<div id="marketSizes" style="display:none">
										<div id="marketSizesFieldDescription" class="fieldDescription" style="background-color: white">
											Configure el tamaño de los mercados del juego. 
										</div>
										<div id="marketSizesFields">
											<?php $this->gameTables($this, "marketsSizes");?>			
										</div>
										<div id="marketSizesEvolutionFields">
											<?php $this->gameTables($this, "marketsSizesEvolution");?>			
										</div>
									</div>
									<div class="fieldCategory fieldDescription" id="channelWeightsButton">
										2. Porcentaje de Ventas por Canal. <!-- Porcentaje de Ventas por Canal></!-->
									</div>
									<div id="channelWeightsFieldsErrors" class="fieldErrors">
									</div>
									<div id="channelWeights" style="display:none">
										<div id="channelWeightsFieldDescription" class="fieldDescription" style="background-color: white">
											Introduzca el porcentaje de ventas de cada canal sobre el tamaño de los mercados en cada una de las rondas. 
										</div>
										<div id="channelWeightsFields">
											<?php $this->gameTables($this, "marketsChannelsWeights");?>						
										</div>
									</div>
									<div class="fieldCategory fieldDescription" id="pricesFieldButton">
										3. Precios. <!-- Precios></!-->
									</div>
									<div id="pricesFieldsErrors" class="fieldErrors">
									</div>
									<div id="pricesField" style="display:none">
										<div id="pricesFieldDescription" class="fieldDescription" style="background-color: white">
											Configure los rangos de precios para cada uno de los productos del juego. 
										</div>
										<div id="pricesFields">
											<?php $this->gameTables($this, "marketsPrices");?>	
										</div>
										<div id="marketPricessEvolutionFields">
											<?php $this->gameTables($this, "marketsPricesEvolution");?>
										</div>
									</div>
									<div class="fieldCategory fieldDescription" id="advertisingFieldButton">
										4. Publicidad. <!-- Ponderaciones Publicidad></!-->
									</div>
									<div id="advertisingFieldsErrors" class="fieldErrors">
									</div>
									<div id="advertisingField" style="display:none">
										<div id="advertisingFieldDescription" class="fieldDescription" style="background-color: white">
											Introduzca los ideales de inversión para cada producto en cada uno de los medios de publicidad del juego.
										</div>
										<div id="advertisingFields">
											<?php $this->gameTables($this, "marketsAdvertisingWeights");?>												
										</div>
										<div id="advertisingEvolutionFields">
											<?php $this->gameTables($this, "marketsAdvertisingWeightsEvolution");?>
										</div>
									</div>
									<div class="fieldCategory fieldDescription" id="trademktFieldButton">
										5. Trade MKT. <!-- Ponderaciones Trade MKT></!-->
									</div>
									<div id="trademktFieldsErrors" class="fieldErrors">
									</div>
									<div id="trademktField" style="display:none">
										<div id="trademktFieldDescription" class="fieldDescription" style="background-color: white">
											Introduzca los ideales de inversión para cada producto en cada uno de los mecanismos de trade MKT del juego.
										</div>
										<div id="trademktFields">
											<?php $this->gameTables($this, "marketsTradeMktWeights");?>												
										</div>
										<div id="trademktEvolutionFields">
											<?php $this->gameTables($this, "marketsTradeMktWeightsEvolution");?>
										</div>
									</div>
									<div class="fieldCategory fieldDescription" id="fidelityFieldButton">
										6. Fidelidad <!-- Fidelidad></!-->
									</div>
									<div id="fidelityFieldsErrors" class="fieldErrors">
									</div>
									<div id="fidelityField" style="display:none">
										<div id="fidelityFieldDescription" class="fieldDescription" style="background-color: white">
											Configure porcentualmente (%) el coeficiente de fidelidad de los mercados que van a ser simulados. 
										</div>
										<div id="fidelityFields">
											<?php $this->gameTables($this, "marketsFidelity");?>	
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
			<form id="formularioModulos" name="game_config" method="post">
				<input type="text" style="display:none" value="dummy" name="formularioModul">
				<div id="modulos">
					<div id="modulos_tabs">
						<div id="menu_modulos">
							<ul>
								<li><a href="#production_logistica">Producción y Logística</a></li>
								<li><a href="#rrhh">Recursos Humanos</a></li>
								<li><a href="#marketing">Marketing</a></li>
								<li><a href="#estudios_mercado">Estudios de mercado</a></li>
								<li><a href="#finanzas">Finanzas</a></li>
							</ul>
						</div>
						<div id="production_logistica">
							<div id="productionParametersFields"> 
								<div class="fieldCategory fieldDescription" id="productionTimesFieldContainerButton">
									1. Tiempos de Producción. <!-- Tiempos de producción></!-->
								</div>
								<div id="productionTimesFieldsErrors" class="fieldErrors">
								</div>
								<div id="productionTimesFieldContainer" style="display:none">
									<div id="productionTimesFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los tiempos de producción (minutos). 
									</div>
									<div id="productionTimesFields">
										<?php $this->gameTables($this, "pr_productionTimes");?>						
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="productionCostsFieldContainerButton">
									2. Costes de Producción. <!-- Costes de producción></!-->
								</div>
								<div id="productionCostsFieldsErrors" class="fieldErrors">
								</div>
								<div id="productionCostsFieldContainer" style="display:none">
									<div id="productionCostsFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los costes de producción. 
									</div>
									<div id="productionCostsFields">
										<?php $this->gameTables($this, "pr_productionCosts");?>									
									</div>
									<div id="productionCostsEvolutionFields">
										<?php $this->gameTables($this, "pr_productionCostsEvolution");?>
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="distributionCostsFieldContainerButton">
									3. Costes de Distribución. <!-- Costes de distribución></!-->
								</div>
								<div id="distributionCostsFieldsErrors" class="fieldErrors">
								</div>
								<div id="distributionCostsFieldContainer" style="display:none">
									<div id="distributionCostsFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los costes de distribución. 
									</div>
									<div id="distributionCostsFields">				
										<?php $this->gameTables($this, "pr_distributionCosts");?>												
									</div>
									<div id="distributionCostsEvolutionFields">
										<?php $this->gameTables($this, "pr_distributionCostsEvolution");?>
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="rawMaterialsFieldContainerButton">
									4. Costes de Abastecimiento. <!-- Costes de abastecimiento></!-->
								</div>
								<div id="rawMaterialsFieldsErrors" class="fieldErrors">
								</div>								
								<div id="rawMaterialsFieldContainer" style="display:none">
									<div id="rawMaterialsFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los costes de abastecimiento. 
									</div>
									<div id="rawMaterialsFields">				
										<?php $this->gameTables($this, "pr_rawMaterialsCosts");?>																	
									</div>
									<div id="rawMaterialsEvolutionFields">
										<?php $this->gameTables($this, "pr_rawMaterialsCostsEvolution");?>
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="suppliersFieldContainerButton">
									5. Pago a proveedores. <!-- Configuración de Proveedores></!-->
								</div>
								<div id="suppliersFieldsErrors" class="fieldErrors">
								</div>
								<div id="suppliersFieldContainer" style="display:none">
									<div id="suppliers" class="fieldDescription" style="background-color: white">
										Configure los recargos por aplazamiento del pago (%). 
									</div>
									<div id="suppliersFields">
										<?php $this->gameTables($this, "pr_suppliers");?>																				
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="organizationFieldContainerButton">
									6. Organización, Infraestructura y Personal. <!-- Configuración de Proveedores></!-->
								</div>
								<div id="organizationFieldsErrors" class="fieldErrors">
								</div>
								<div id="organizationFieldContainer" style="display:none">
									<div id="organizationFieldDescription" class="fieldDescription" style="background-color: white">
										Determine la configuración de las plantas de producción. 
									</div>
									<div id="organizationFields">				
										<?php $this->gameTables($this, "pr_productionOrganization");?>																							
									</div>
								</div>
							</div>
						</div>
						<div id="rrhh">
							<div id="human_resourcesParametersFields"> 
								<div class="fieldCategory fieldDescription" id="hrCostsButton">
									1. Costes por empleado y a&ntilde;o. <!-- Costes por empleado y año></!-->
								</div>
								<div id="hrCostsFieldsErrors" class="fieldErrors">
								</div>
								<div id="hrCostsContainer">
									<div id="hrCostsFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los costes de personal empleado en sus centros de producción. 
									</div>
									<div id="hrCostsFields">				
										<?php $this->gameTables($this, "hr_staffCosts");?>			
									</div>
									<div id="hrCostsEvolutionFields">
										<?php $this->gameTables($this, "hr_staffCostsEvolution");?>
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="hrRegionsProfileButton">
									2. Perfil de las regiones. <!-- Costes por empleado y año></!-->
								</div>
								<div id="hrRegionsProfileFieldsErrors" class="fieldErrors">
								</div>
								<div id="hrRegionsProfileContainer">
									<div id="hrRegionsProfileFieldDescription"  class="fieldDescription" style="background-color: white">
										Configure el perfil de laboral de las regiones. 
									</div>
									<div id="hrRegionsProfileFields">				
										<?php $this->gameTables($this, "hr_regionsProfiles");?>				
									</div>	
								</div>
							</div>
						</div>
						<div id="marketing">
							<div id="marketingParametersFields"> 
								<div class="fieldCategory fieldDescription" id="mkChannelsCostsButton">
									1. Costes Canales de distribución. <!-- Costes canales de Distribución></!-->
								</div>
								<div id="mkChannelsCostsFieldsErrors" class="fieldErrors">
								</div>
								<div id="mkChannelsCostsContainer">
									<div id="mkChannelsCostsFieldDescription"  class="fieldDescription" style="background-color: white">
										Configure costes de los canales de distribución. 
									</div>
									<div id="mkChannelsCostsFields">
										<?php $this->gameTables($this, "mk_channelsCosts");?>			
									</div>
									<div id="mkChannelsCostsEvolutionFields">
										<?php $this->gameTables($this, "mk_channelsCostsEvolution");?>
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="mkChargeTimesButton">
									2. Plazo de cobro a clientes. <!-- Plazos de cobro a clientes></!-->
								</div>
								<div id="mkChargeTimesFieldsErrors" class="fieldErrors">
								</div>
								<div id="mkChargeTimesContainer">
									<div id="mkChargeTimesFieldDescription" class="fieldDescription" style="background-color: white">
										Fije el periodo de cobro (en meses) según los canales de distribución. 
									</div>
									<div id="mkChargeTimesFields">
										<?php $this->gameTables($this, "mk_channels_incomesTerms");?>						
									</div>
								</div>
							</div>
						</div>
						<div id="estudios_mercado">
							<div id="marketResearchesParametersFields"> 
								<div class="fieldCategory fieldDescription" id="marketResearchesCostsButton">
									1. Costes contratación de estudios.
								</div>
								<div id="marketResearchesCostsFieldsErrors" class="fieldErrors">
								</div>
								<div id="marketResearchesCostsContainer">
									<div id="marketResearchesCostsFieldDescription" class="fieldDescription" style="background-color: white">
										Configure costes de contratación de cada uno de los estudios de mercado. 
									</div>
									<div id="marketResearchesCostsFields">
										<?php $this->gameTables($this, "marketResearchesCosts");?>			
									</div>
								</div>
							</div>
						</div>
						<div id="finanzas">
							<div id="financeParametersFields"> 
								<div class="fieldCategory fieldDescription" id="fiCashflowButton">
									1. Flujos de caja. <!-- Flujos de Caja></!-->
								</div>
								<div id="fiCashflowFieldsErrors" class="fieldErrors">
								</div>
								<div id="fiCashflowContainer">
									<div id="fiCashflowFieldDescription" class="fieldDescription" style="background-color: white">
										Configure parámetros sobre flujos de caja. 
									</div>
									<div id="fiCashflowFields">				
										<?php $this->gameTables($this, "fi_cashflowParameters");?>												
									</div>
								</div>
								<div class="fieldCategory fieldDescription" id="interestRateButton">
									2. Intereses de la financiación. <!-- Intereses financiacion></!-->
								</div>
								<div id="interestRateFieldsErrors" class="fieldErrors">
								</div>
								<div id="interestRateContainer">
									<div id="interestRateFieldDescription" class="fieldDescription" style="background-color: white">
										Configure los intereses para los cr&eacute;ditos ofrecidos. 
									</div>
									<div id="interestRateFields">				
										<?php $this->gameTables($this, "fi_interestRateParameters");?>												
									</div>
								</div>
								<!-- VERO -->
								<div class="fieldCategory fieldDescription" id="investmentButton">
									3. Tipos de inversión. <!-- Tipos de inversión></!-->
								</div>
								<div id="investmentFieldsErrors" class="fieldErrors">
								</div>
								<div id="investmentContainer">
									<div id="investmentFieldDescription" class="fieldDescription" style="background-color: white">
										Configure parámetros sobre las inversiones. 
									</div>
									<div id="investmentFields">				
										<?php $this->gameTables($this, "investmentParameters");?>												
									</div>
								</div>
								<!-- VERO -->
							</div>
						</div>
					</div>
				</div>		
			</form>
			<div id="botones">
				<input class=button type="button" value="Guardar General" onclick="guardarGeneral();">
				<input class=button type="button" value="Guardar Parámetros" onclick="guardarParametros();">
				<input class=button type="button" value="Guardar Módulos" onclick="guardarModulos();">
			</div>
			<script>
				function guardarGeneral(){
					var optionsGeneral = { 
						//target:        '#output1',   // target element(s) to be updated with server response 
						beforeSubmit:  showRequestGeneral,  // pre-submit callback 
						success:       showResponse  // post-submit callback 
				 
						// other available options: 
						//url:       url         // override for form's 'action' attribute 
						//type:      type        // 'get' or 'post', override for form's 'method' attribute 
						//dataType:  null        // 'xml', 'script', or 'json' (expected server response type) 
						//clearForm: true        // clear all form fields after successful submit 
						//resetForm: true        // reset the form after successful submit 
				 
						// $.ajax options can be used here too, for example: 
						//timeout:   3000 
					}
					$('#formularioGeneral').ajaxSubmit(optionsGeneral); 
					styleChangeBeforeAlert();
				}
				function guardarParametros(){

					var optionsParametros = { 
						beforeSubmit:  showRequestParametros,  // pre-submit callback 
						success:       showResponse  // post-submit callback 
					}
					$('#formularioParametros').ajaxSubmit(optionsParametros); 
					styleChangeBeforeAlert();
					
				}
				
				function guardarModulos(){
					var optionsModulos = { 
						beforeSubmit:  showRequestModulos,  // pre-submit callback 
						success:       showResponse  // post-submit callback 
					}
					$('#formularioModulos').ajaxSubmit(optionsModulos); 
					styleChangeBeforeAlert();
				}
				// wait for the DOM to be loaded 
				
				function showRequestGeneral(formData, jqForm, options) {
				
					document.getElementById('validationGeneralStartup').style.display='block';
					document.getElementById('light1').style.display='block'; 
					document.getElementById('fade1').style.display='block'; 
					var validacionCorrecta1;
					try {
						//alert('Check the form submission, it is not correct now'); 
						// here we could return false to prevent the form from being submitted; 
						// returning anything other than false will allow the form submit to continue 
						validacionCorrecta1 = validateForm("formularioGeneral");
					}
					catch (ex) {
						alert(ex.toString());
						validacionCorrecta1 = false;
					}
					
					return validacionCorrecta1;
				};

				function showRequestParametros(formData, jqForm, options) {
				
					document.getElementById('validationParamsStartup').style.display='block';
					document.getElementById('light1').style.display='block'; 
					document.getElementById('fade1').style.display='block'; 
					var validacionCorrecta2;
					try {
						//alert('Check the form submission, it is not correct now'); 
						// here we could return false to prevent the form from being submitted; 
						// returning anything other than false will allow the form submit to continue; 
						validacionCorrecta2 = validateForm("formularioParametros");
					}
					catch (ex) {
						alert(ex.toString());
						validacionCorrecta2 = false;
					}
					
					return validacionCorrecta2;
				};				
				
				function showRequestModulos(formData, jqForm, options) {
					document.getElementById('validationModulosStartup').style.display='block';
					document.getElementById('light1').style.display='block'; 
					document.getElementById('fade1').style.display='block'; 				
					var validacionCorrecta3;
					alert("Why are you here?");
					try {
						//alert('Check the form submission, it is not correct now'); 
						// here we could return false to prevent the form from being submitted; 
						// returning anything other than false will allow the form submit to continue;
						validacionCorrecta3 = validateForm("formularioModulos");
					}
					catch (ex) {
						alert(ex.toString());
						validacionCorrecta3 = false;
					}
					alert(validacionCorrecta3);
					
					return validacionCorrecta3;
				};
				
				function showResponse(responseText, statusText, xhr, $form)  { 
					// for normal html responses, the first argument to the success callback 
					// is the XMLHttpRequest object's responseText property 
				 
					// if the ajaxForm method was passed an Options Object with the dataType 
					// property set to 'xml' then the first argument to the success callback 
					// is the XMLHttpRequest object's responseXML property 
				 
					// if the ajaxForm method was passed an Options Object with the dataType 
					// property set to 'json' then the first argument to the success callback 
					// is the json data object returned by the server 
					alert("Validando show");
					document.getElementById('validationGeneralStartup').style.display='none';
					document.getElementById('validationGeneralCompleted').style.display='none';
					document.getElementById('validationParamsStartup').style.display='none';
					document.getElementById('validationParamsCompleted').style.display='none';
					document.getElementById('validationModulosStartup').style.display='none';
					document.getElementById('validationModulosCompleted').style.display='none';
					document.getElementById('light1').style.display='none'; 
					document.getElementById('fade1').style.display='none'; 
					$().toastmessage('showSuccessToast', "Formulario guardado correctamente");
					
				};
				//creación de las pestañas de general, parámetros y modulos
				$(function() {
					$( "#formulario" ).tabs();
				});
				//creación de las pestañas de la sección general
				$(function() {
					$( "#general_tabs" ).tabs();
				});
				//creación de las pestañas de la sección parámetros
				$(function() {
					$( "#parametros_tabs" ).tabs();
				});
				//creación de las pestañas de la sección módulos
				$(function() {
					$( "#modulos_tabs" ).tabs();
				});
				//funciones para expandir/contraer los elementos de las pestañas
				$( "#productsFieldDescription" ).click(function() {
					$( "#productsParametersContainer" ).toggle( "easeInElastic" );
				});
				$( "#qualitiesFieldDescription" ).click(function() {
					$( "#qualitiesParametersContainer" ).toggle( "easeInElastic" );
				});
				$( "#functionalityFieldDescription" ).click(function() {
					$( "#functionalitiesParametersContainer" ).toggle( "easeInElastic" );
				});
				$( "#regionsFieldDescription" ).click(function() {
					$( "#regionesContainer" ).toggle( "easeInElastic" );
				});
				$( "#channelsFieldDescription" ).click(function() {
					$( "#channelsParametersContainer" ).toggle( "easeInElastic" );
				});
				$( "#mediaFieldDescription" ).click(function() {
					$( "#medios_publicitariosContainer" ).toggle( "easeInElastic" );
				});
				$( "#initiativesFieldDescription" ).click(function() {
					$( "#initiativesContainer" ).toggle( "easeInElastic" );
				});
				$( "#marketSizesButton" ).click(function() {
					$( "#marketSizes" ).toggle( "easeInElastic" );
				});
				$( "#channelWeightsButton" ).click(function() {
					$( "#channelWeights" ).toggle( "easeInElastic" );
				});
				$( "#pricesFieldButton" ).click(function() {
					$( "#pricesField" ).toggle( "easeInElastic" );
				});
				$( "#advertisingFieldButton" ).click(function() {
					$( "#advertisingField" ).toggle( "easeInElastic" );
				});
				$( "#trademktFieldButton" ).click(function() {
					$( "#trademktField" ).toggle( "easeInElastic" );
				});
				$( "#fidelityFieldButton" ).click(function() {
					$( "#fidelityField" ).toggle( "easeInElastic" );
				});
				$( "#productionTimesFieldContainerButton" ).click(function() {
					$( "#productionTimesFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#productionCostsFieldContainerButton" ).click(function() {
					$( "#productionCostsFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#distributionCostsFieldContainerButton" ).click(function() {
					$( "#distributionCostsFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#rawMaterialsFieldContainerButton" ).click(function() {
					$( "#rawMaterialsFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#suppliersFieldContainerButton" ).click(function() {
					$( "#suppliersFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#organizationFieldContainerButton" ).click(function() {
					$( "#organizationFieldContainer" ).toggle( "easeInElastic" );
				});
				$( "#hrCostsButton" ).click(function() {
					$( "#hrCostsContainer" ).toggle( "easeInElastic" );
				});
				$( "#hrRegionsProfileButton" ).click(function() {
					$( "#hrRegionsProfileContainer" ).toggle( "easeInElastic" );
				});
				$( "#mkChannelsCostsButton" ).click(function() {
					$( "#mkChannelsCostsContainer" ).toggle( "easeInElastic" );
				});
				$( "#mkChargeTimesButton" ).click(function() {
					$( "#mkChargeTimesContainer" ).toggle( "easeInElastic" );
				});
				$( "#marketResearchesCostsButton" ).click(function() {
					$( "#marketResearchesCostsContainer" ).toggle( "easeInElastic" );
				});
				$( "#fiCashflowButton" ).click(function() {
					$( "#fiCashflowContainer" ).toggle( "easeInElastic" );
				});
				$( "#interestRateButton" ).click(function() {
					$( "#interestRateContainer" ).toggle( "easeInElastic" );
				});
				//VERO
				$( "#InvestmentButton" ).click(function() {
					$( "#investmentContainer" ).toggle( "easeInElastic" );
				});
				//VERO
			</script>
			
		</div>
		<div id="light1" style="display: none;position: fixed;top: 25%;left: 25%;width: 50%;height: 50%;border: 16px solid #336699;background-color: white;z-index:1002;overflow: auto;">
			<div id="validationGeneralStartup" style="display:none">Se va a iniciar la validación del formulario General</div>
			<div id="validationParamsStartup" style="display:none">Se va a iniciar la validación del formulario de Parámetros</div>
			<div id="validationModulosStartup" style="display:none">Se va a iniciar la validación del formulario de Módulos</div>
			<div id="validationGeneralCompleted" style="display:none">Se ha terminado la validación del formulario General. Espere a que se guarde el formulario.</div>
			<div id="validationParamsCompleted" style="display:none">Se ha terminado la validación del formulario de Parámetros. Espere a que se guarde el formulario.</div>
			<div id="validationModulosCompleted" style="display:none">Se ha terminado la validación del formulario de Módulos. Espere a que se guarde el formulario.</div>
		</div>
		<div id="fade1" style="display: none; position: fixed;top: 0%;left: 0%;width: 100%;height: 100%;background-color: black;z-index:1001;-moz-opacity: 0.8;opacity:.80;filter: alpha(opacity=80);">
		</div>
<?php }//if juego definido
else{ //mostramos todos los juegos?>
	<h1>Editar plantilla o juego.</h1>		
	
	<?php if (isset($this->games) && count($this->games)){?>
	<form method="get" action="">
		<div class="fieldHeader">
			Juego.
		</div>
		<p>Seleccione juego a editar.</p>
		<div id="gamesField" class="fieldDiv">
			<select name='game_id' onchange="this.form.submit()">
			<?php foreach($this->games as $game){?>
				<option value="<?php echo $this->escape($game->id)?>"><?php echo $this->escape($game->name)?></option>
			<?php }?>
			</select>
			<!--<div class="buttonsDiv">
				<input class=button type="submit" value="Editar">
			</div>-->
		</div>
	</form>
	<?php } // if  
	else {?>
		<p>No hay juegos en la plataforma.</p>
	<?php }?>
	<?php if (isset($this->templates) && count($this->templates)){?>
	<form method="get" action="">
		<div class="fieldHeader">
			Plantillas.
		</div>
		<p>Seleccione plantilla a editar.</p>
		<div id="gamesField" class="fieldDiv">
			<select name='game_id' onchange="this.form.submit()">
			<?php foreach($this->templates as $template){?>
				<option value="<?php echo $this->escape($template->id)?>"><?php echo $this->escape($template->name)?></option>
			<?php }?>
			</select>
			<!--<div class="buttonsDiv">
				<input class=button type="submit" value="Editar">
			</div>-->
		</div>
	</form>
	<?php } // if  
	else {?>
		<p>Seleccione juego a editar.</p>
	<?php }?>
<?php } ?>
</div>