<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/outcomes.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/display.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/bar.css');?>	
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui-outcomes-theme/jquery-ui-1.10.3.custom.css');?>

<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/generalScripts.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-1.9.1.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery-ui-1.10.3.custom.min.js', $type = 'text/javascript')?>

<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery.progressbar.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/lib/jquery.progressbar.min.js', $type = 'text/javascript')?>

<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/loading.css');?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/loading.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/outcomes_user.js', $type = 'text/javascript')?>

<script type="text/javascript" src="//www.google.com/jsapi"></script>
<script type="text/javascript">
	//carga de los paquetes necesarios de la api de google charts
	
    google.load('visualization', '1', {packages: ['table', 'controls']});
</script>


<div id='content'>
<div id="light" class="white_content">
	<div id="imgLOAD" style="text-align:center;">
			<br /><br /><br /><br /><br />
			<b>Cargando...</b><br /><br /><br />
			<img src="/images/loading.gif" style="float:center"/>
		</div>
	</div>
	<script type="text/javascript">
		window.onload = detectarCarga();
	</script>

	<div id="image_and_button">
		<img src="/images/outcomes_2.gif" alt="i+d" width="90" height="110"/>
	</div>
	<div class="outcomes_header1">
		<div>
			<div>
				<div style="float: left"><strong>Juego:</strong> <?php echo $this->game['name']?> <a href="<?php echo $this->baseUrl()?>/game/view?game_id=<?php echo $this->game['id']?>">(volver a rondas)</a></div>
				<div style="float: right"><strong>Ronda:</strong> <?php echo $this->round_number?></div>
				</br></br>
			</div>
			<div id="outcomes_nav">
				<ul>
					<li><a id='pr_tab' class="outcomes_nav_menu isActive" href=#>Producci&oacute;n</a></li>
					<li><a id='sales_tab' class="outcomes_nav_menu" href=#>Ventas</a></li>
					<li><a id='stocks_tab' class="outcomes_nav_menu" href=#>Stocks</a></li>
					<li><a id='display_evolution_tab' class="outcomes_nav_menu" href=#>Cuotas de mercado</a></li>
					<li><a id='display_tab' class="outcomes_nav_menu" href=#>Indicadores internos</a></li>
					<li><a id='res_tab' class="outcomes_nav_menu" href=#>Ctas. Resultados</a></li>
					<li><a id='balance_sheet_tab' class="outcomes_nav_menu" href=#>Balance</a></li>
					<li><a id='performance_tab' class="outcomes_nav_menu" href=#>Ratios financieros</a></li>
				</ul>
			</div>
		</div>
		</br>
		<div class="outcomes_publication_menu">
			<form method="post" style="width: 500px; margin-left: auto; margin-right: auto;">
			<?php if (($this->outcomes->isPublished($this->game['id'], $this->round_number))==0){?>
				<span class="warning">Resultados no publicados</span><br>
				<input type="submit" name="publish" value="Publicar">
				<input type="button" name="export" onclick="location.href='<?php echo $this->url(array('controller'=>'game', 'action'=>'download')) . "?game_id=".$this->game['id']."&round_number=".$this->round_number?>'" value="Exportar">
			<?php } else {?>
				<span class="info_ok">Resultados públicos</span><br>
				<input type="submit" name="publish" value="Ocultar">
				<input type="button" name="export" onclick="location.href='<?php echo $this->url(array('controller'=>'game', 'action'=>'download')) . "?game_id=".$this->game['id']."&round_number=".$this->round_number?>'" value="Exportar">
			<?php }?>
			</form>				
		</div>
	</div>	
	
	<div id="outcomes_container">
		<div id="production_outcomes" class="tab">			
				<table class="outcomes_table">
					<thead>
						<th colspan='2' class='invisible'>
							<h1 style="color:#B22222">PRODUCCI&Oacute;N</h1>
						</th>
						<?php 
							foreach ($this->companies as $company){?>
						<?php $counter=0;
								  foreach ($this->regions as $region){
									$counter++;    
								  }
							?>
						<th colspan='<?php echo ($counter)?>' class="vertical_group_open">
							<strong><?php echo $company['name']?></strong>
						</th>

						<?php } ?>
					</thead>
					<thead>
						<th colspan='2' class='invisible'>
						</th>
						<?php foreach ($this->companies as $company){
							$newVGroup=true;
							?>					
							<?php foreach ($this->regions as $region){
								if ($newVGroup){
									$vertical_class='vertical_group_open';
									$newVGroup=false;
								}else{
									$vertical_class='';
								}?>
								<th class="<?php echo $vertical_class ?>">
									<?php echo ($region['name'])?>
								</th>
						    <?php }//for region ?>
					    <?php }//for company ?>
					</thead>
					<?php 
					$hgroup=0;
					foreach ($this->products as $product){	
						if($this->game_product_availability['product_number_'.$product['product_number']]==1){
							$hgroup++;
							$hor_class='hor_group_odd';
							if ($hgroup % 2 == 0){
								$hor_class='hor_group_even';
							}
							foreach ($this->channels as $channel){
								?>					
								<tr>
									<td class="<?php echo $hor_class?>">
										<?php if ($channel['channel_number']==1){
											echo ('Producto: '.$product['name']);
										}?>
									</td>
									<td class="<?php echo $hor_class?>">
										<?php echo ('Canal: '.$channel['name'])?>
									</td>
								<?php foreach ($this->companies as $company){	
									    $newVGroup=true;?>						
								<?php
								foreach ($this->regions as $region){
									if ($newVGroup){
										$vertical_class='vertical_group_open';
										$newVGroup=false;
									}else{
										$vertical_class='';
									}?>
									<td class="<?php echo $hor_class.' '.$vertical_class?>">
										<?php echo number_format($this->outcomes_production_units['company_'.$company['id']]
																					['product_'.$product['product_number']]
																			  		['region_'.$region['region_number']]
																			  		['channel_'.$channel['channel_number']],0, '.', ',')?>
									</td>
								<?php }//for region 
							 }//for company?>			
							</tr>
					<?php }//for channel
						}//availability
					}//for product
						?>
					</table>
		</div>			
		<div id="sales_outcomes" class="tab">
		
			<table class="outcomes_table">
				<thead>
					<th colspan='2' class='invisible'>
						<h1 style="color:#B22222">VENTAS</h1>
					</th>
					<?php foreach ($this->companies as $company){?>
							<?php $counter=0;
								  foreach ($this->regions as $region){
									$counter++;    
								  }
							?>
						<th colspan='<?php echo (2*$counter)?>' class="vertical_group_open">	
							<strong>
							<?php echo $company['name']?>
							</strong>
						</th>
					<?php } ?>
				</thead>
				<thead>
					<th colspan='2' class='invisible'>
					</th>
					<?php foreach ($this->companies as $company){
						$newVGroup=true;
						?>					
						<?php foreach ($this->regions as $region){
							if ($newVGroup){
								$vertical_class='vertical_group_open';
								$newVGroup=false;
							}else{
								$vertical_class='';
							}?>
							<th colspan='2' class="<?php echo $vertical_class ?>">
								<?php echo ($region['name'])?>
							</th>
					    <?php }//for region ?>
				    <?php }//for company ?>
				</thead>
				<thead>
					<th colspan='2' class='invisible'>
					</th>
					<?php foreach ($this->companies as $company){
						$newVGroup=true;
						?>					
						<?php foreach ($this->regions as $region){
							if ($newVGroup){
								$vertical_class='vertical_group_open';
								$newVGroup=false;
							}else{
								$vertical_class='';
							}?>
							<th class="<?php echo $vertical_class ?>">
								Ventas
							</th>
							<th>
								Precio
							</th>
					    <?php }//for region ?>
				    <?php }//for company ?>
				</thead>
				<?php 
				$hgroup=0;
				foreach ($this->products as $product){
					if($this->game_product_availability['product_number_'.$product['product_number']]==1){
						$hgroup++;
						$hor_class='hor_group_odd';
						if ($hgroup % 2 == 0){
							$hor_class='hor_group_even';
						}
						foreach ($this->channels as $channel){
							?>					
							<tr>
								<td class="<?php echo $hor_class?>">
									<?php if ($channel['channel_number']==1){
										echo ('Producto: '.$product['name']);
									}?>
								</td>
								<td class="<?php echo $hor_class?>">
									<?php echo ('Canal: '.$channel['name'])?>
								</td>
							<?php foreach ($this->companies as $company){	
								    $newVGroup=true;?>						
							<?php
							foreach ($this->regions as $region){
								if ($newVGroup){
									$vertical_class='vertical_group_open';
									$newVGroup=false;
								}else{
									$vertical_class='';
								}?>
								<td class="<?php echo $hor_class.' '.$vertical_class?>">
									<?php $total_sales['product_'.$product['product_number']]['region_'.$region['region_number']]+=$this->outcomes_sales_units['company_'.$company['id']]['product_'.$product['product_number']]['region_'.$region['region_number']]['channel_'.$channel['channel_number']];
															echo number_format($this->outcomes_sales_units['company_'.$company['id']]
																				['product_'.$product['product_number']]
																		  		['region_'.$region['region_number']]
																		  		['channel_'.$channel['channel_number']],0, '.', ',')?>
								</td>
								<td nowrap class="<?php echo $hor_class.' '?>">
									<?php echo number_format($this->outcomes_prices['company_'.$company['id']]
																				['product_'.$product['product_number']]
																		  		['channel_'.$channel['channel_number']]
																		  		['region_'.$region['region_number']],
															  2, '.', ',').' €'?>
								</td>
							<?php }//for region 
						 }//for company?>			
						</tr>
				<?php }//for channel
					}//availability
				}//for product
					?>
				</table>
				<br/>
			<table class="outcomes_table">
				<thead>
					<th colspan='2' class='invisible'>
						<h1 style="color:#B22222">VENTAS TOTALES POR MERCADOS</h1>
					</th>
							<?php $counter=0;
								  foreach ($this->regions as $region){
									$counter++;    
								  }
							?>
						<th colspan='<?php echo (2*$counter)?>' class="vertical_group_open">	

						</th>
				</thead>
				<thead>
					<th colspan='2' class='invisible'>
					</th>
					
						<?php $newVGroup=true;
						?>					
						<?php foreach ($this->regions as $region){
							if ($newVGroup){
								$vertical_class='vertical_group_open';
								$newVGroup=false;
							}else{
								$vertical_class='';
							}?>
							<th colspan='2' class="<?php echo $vertical_class ?>">
								<?php echo ($region['name'])?>
							</th>
					    <?php }//for region ?>
				    
				</thead>
				<thead>
					<th colspan='2' class='invisible'>
					</th>
						<?php $newVGroup=true;?>					
						<?php foreach ($this->regions as $region){
							$newVGroup=true;
							if ($newVGroup){
								$vertical_class='vertical_group_open';
								$newVGroup=false;
							}else{
								$vertical_class='';
							}?>
							<th class="<?php echo $vertical_class ?>">
								Ventas Acumuladas
							</th>
							<th class="<?php echo $vertical_class ?>" style="color:#808080">
								Tamaño Mercado
							</th>
					    <?php }//for region ?>
				</thead>
				<?php 
				$hgroup=0;
				foreach ($this->products as $product){
					if($this->game_product_availability['product_number_'.$product['product_number']]==1){
						$hgroup++;
						$hor_class='hor_group_odd';
						if ($hgroup % 2 == 0){
							$hor_class='hor_group_even';
						}
							?>					
							<tr>
								<td class="<?php echo $hor_class?>">
								</td>
								<td class="<?php echo $hor_class?>">
									<?php if ($channel['channel_number']==1){
										echo ('Producto: '.$product['name']);
									}?>
								</td>
							<?php 	$newVGroup=true;?>						
							<?php
							foreach ($this->regions as $region){
								$newVGroup=true;
								if ($newVGroup){
									$vertical_class='vertical_group_open';
									$newVGroup=false;
								}else{
									$vertical_class='';
								}?>
								<td class="<?php echo $hor_class.' '.$vertical_class?>">
									<?php echo number_format($total_sales['product_'.$product['product_number']]['region_'.$region['region_number']],0, '.', ',')?>
								</td>
								<td class="<?php echo $hor_class.' '.$vertical_class?>" style="color:#808080">
									<?php echo ($this->outcomes_market_sizes['product_'.$product['product_number']]['region_'.$region['region_number']])?>
								</td>
							<?php }//for region?>			
						</tr>
			<?php }
				}//for product
					?>
				</table>
		</div>
		
		<div id="stock_outcomes" class="tab">			
				<table class="outcomes_table">
					<thead>
						<th colspan='2' class='invisible'>
							<h1 style="color:#B22222">STOCKS</h1>
						</th>
						<?php 
							foreach ($this->companies as $company){?>
						<?php $counter=0;
								  foreach ($this->regions as $region){
									$counter++;    
								  }
							?>
						<th colspan='<?php echo ($counter)?>' class="vertical_group_open">
								<strong>
								<?php echo $company['name']?>
								</strong>
							</th>

						<?php } ?>
					</thead>
					<thead>
						<th colspan='2' class='invisible'>
						</th>
						<?php foreach ($this->companies as $company){
							$newVGroup=true;
							?>					
							<?php foreach ($this->regions as $region){
								if ($newVGroup){
									$vertical_class='vertical_group_open';
									$newVGroup=false;
								}else{
									$vertical_class='';
								}?>
								<th class="<?php echo $vertical_class ?>">
									<?php echo ($region['name'])?>
								</th>
						    <?php }//for region ?>
					    <?php }//for company ?>
					</thead>
					<?php 
					$hgroup=0;
					foreach ($this->products as $product){
						if($this->game_product_availability['product_number_'.$product['product_number']]==1){
							$hgroup++;
							$hor_class='hor_group_odd';
							if ($hgroup % 2 == 0){
								$hor_class='hor_group_even';
							}
							foreach ($this->channels as $channel){
								?>					
								<tr>
									<td class="<?php echo $hor_class?>">
										<?php if ($channel['channel_number']==1){
											echo ('Producto: '.$product['name']);
										}?>
									</td>
									<td class="<?php echo $hor_class?>">
										<?php echo ('Canal: '.$channel['name'])?>
									</td>
								<?php foreach ($this->companies as $company){	
									    $newVGroup=true;?>						
									<?php
									foreach ($this->regions as $region){
										if ($newVGroup){
											$vertical_class='vertical_group_open';
											$newVGroup=false;
										}else{
											$vertical_class='';
										}?>
										<td class="<?php echo $hor_class.' '.$vertical_class?>">
											<?php echo number_format($this->outcomes_stocks_units['company_'.$company['id']]
																					['product_'.$product['product_number']]
																				  	['region_'.$region['region_number']]
																				  	['channel_'.$channel['channel_number']],0, '.', ',')?>
										</td>
									<?php }//for region 
							 }//for company?>			
							</tr>
					<?php }//for channel
						}//availability
					}//for product
						?>
					</table>
		</div>
		
		<div id="results_outcomes" class="tab">
			<table class="outcomes_table">
				<thead>
					<th colspan='2' class='invisible categories'>
						<h1 style="color:#B22222">CTAS. RESULTADOS</h1>
					</th>					
					<?php foreach ($this->companies as $company){ //Companies array obtenido mediante $this->view->companies = $games->getCompaniesInGame($game_id)?>			
						<th class="vertical_group_open"> <!-- th centra y pone en negrita cada una de los valores de la variable $company-->
							<strong>
							<?php echo $company['name']?>
							</strong>
						</th>

					<?php } ?>
				</thead>
				<thead>
					<th colspan='2'class='invisible categories'>
						<h2 style="color:#800000">INGRESOS</h2>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th class="<?php echo $vertical_class ?>"></th>
				    <?php }//for company ?>
				</thead>
				<?php 
				$hgroup=0;
				$incomes_sum=array();
				foreach($this->channels as $channel){
			
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories"><?php echo $channel['name']?></td>
					<?php 
				
						foreach ($this->companies as $company){
							if (!isset ($incomes_sum[$company['id']])){
								$incomes_sum[$company['id']]=0;
							}
							$incomes=0;
							foreach ($this->products as $product){
								if($this->game_product_availability['product_number_'.$product['product_number']]==1){
									foreach ($this->regions as $region){
										$incomes+=$this->outcomes_sales_incomes['company_'.$company['id']]
																	['product_'.$product['product_number']]
																	['region_'.$region['region_number']]
																	['channel_'.$channel['channel_number']];
									}					
								}
							}
							$incomes_sum[$company['id']]+=$incomes;
						?>
						<td class="<?php echo $hor_class?> vertical_group_open"nowrap><?php echo number_format($incomes, 2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<?php } ?>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Total Ingresos</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($incomes_sum[$company['id']], 2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<thead>
					<th colspan='2'class='invisible categories'>
						<h2 style="color:#800000">GASTOS</h2>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<!-- PRODUCCIÓN -->
				<thead>			
					<th colspan='2' class='invisible categories'>
						<strong><h4>Producción & Logística</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Mantenimiento de Fábricas y Maquinaria</td>
					<?php foreach ($this->companies as $company){
						
						$pr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['pr_fixed_cost'];?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['pr_fixed_cost'], 2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Fabricación de productos</td>
					<?php foreach ($this->companies as $company){
						$pr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['pr_var_costs'];?>
						
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['pr_var_costs'], 2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					
									
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Abastecimiento de materias primas</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<?php 
					$hgroup=2;
				foreach($this->channels as $channel){
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories">&nbsp;&nbsp;&nbsp;<?php echo $channel['name']?></td>
					<?php foreach ($this->companies as $company){
						$pr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['pr_rawMaterials_costs'][$channel['channel_number']];
						?>
						<td class="<?php echo $hor_class?> vertical_group_open"nowrap><?php echo number_format( $this->outcomes_costs[$company['id']]['pr_rawMaterials_costs'][$channel['channel_number']], 2, '.', ',').' €'?>
							</td>
					<?php } ?>
				</tr>
				<?php }?>
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Distribución</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;&nbsp;Gastos de Distribución</td>
					<?php foreach ($this->companies as $company){
						$pr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['pr_distrib_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['pr_distrib_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
				<br/>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total Producción & Logística</a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($pr_costs[$company['id']], 2, '.', ',').' €';?></th>
				    <?php }//for company ?>
				</thead>
				<!-- MARKETING -->
				<thead>			
					<th></th>
					<th class='invisible categories'>
						<strong><h4>Marketing</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){
						$mk_costs[$company['id']]=0;?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Publicidad</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<?php $hgroup=1;
				foreach($this->media as $media){
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories">&nbsp;&nbsp;&nbsp;<?php echo $media['name']?></td>
					<?php foreach ($this->companies as $company){
							$mk_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['mk_advert_costs'][$media['media_number']];
						?>
						<td class="<?php echo $hor_class?> vertical_group_open">
							<?php echo number_format($this->outcomes_costs[$company['id']]['mk_advert_costs'][$media['media_number']],2, '.', ',').' €'?>
						</td>
					<?php } ?>
				</tr>
				<?php } ?>
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Trade MKT</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<?php $hgroup=1;
				foreach($this->trademedia as $trademedia){
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories">&nbsp;&nbsp;&nbsp;<?php echo $trademedia['name']?></td>
					<?php foreach ($this->companies as $company){
							$mk_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['mk_trade_costs'][$trademedia['trademedia_number']];
						?>
						<td class="<?php echo $hor_class?> vertical_group_open">
							<?php echo number_format($this->outcomes_costs[$company['id']]['mk_trade_costs'][$trademedia['trademedia_number']],2, '.', ',').' €'?>
						</td>
					<?php } ?>
				</tr>
				<?php } ?>
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Gasto por ventas</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<?php 
					$hgroup=1;
				foreach($this->channels as $channel){
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories">&nbsp;&nbsp;&nbsp;<?php echo $channel['name']?></td>
					<?php foreach ($this->companies as $company){
						$mk_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['mk_sales_costs'][$channel['channel_number']];
					?>
					<td class="<?php echo $hor_class?> vertical_group_open">
						<?php echo number_format($this->outcomes_costs[$company['id']]['mk_sales_costs'][$channel['channel_number']],2, '.', ',').' €'?>
					</td>
					<?php } ?>
				</tr>
				<?php }?>
				<thead>
					<th class="hor_group_odd categories"></th>
					<th class="hor_group_odd categories">Gasto fijo por canales de distribución</th>
					<?php foreach ($this->companies as $company){ ?>
						<th></th>
					<?php } ?>
				</thead>
				<?php 
					$hgroup=1;
				foreach($this->channels as $channel){
					$hgroup++;
					$hor_class='hor_group_odd';
					if ($hgroup % 2 == 0){
						$hor_class='hor_group_even';
					}?>
				<tr>
					<td class="<?php echo $hor_class?> categories"></td>
					<td class="<?php echo $hor_class?> categories">&nbsp;&nbsp;&nbsp;<?php echo $channel['name']?></td>
					<?php foreach ($this->companies as $company){
						$mk_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['mk_fixed_costs'][$channel['channel_number']];
						?>
						<td class="<?php echo $hor_class?> vertical_group_open"nowrap><?php echo number_format( $this->outcomes_costs[$company['id']]['mk_fixed_costs'][$channel['channel_number']],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<?php }?>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total Marketing</a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($mk_costs[$company['id']],2, '.', ',').' €';?></th>
				    <?php }//for company ?>
				</thead>
				<!-- PERSONAL -->
				<thead>			
					<th></th>
					<th class='invisible categories'>
						<strong><h4>Recursos Humanos</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){
						$hr_costs[$company['id']]=0;?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Contratación</td>
					<?php foreach ($this->companies as $company){
						$hr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['hr_hiring_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['hr_hiring_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Formación</td>
					<?php foreach ($this->companies as $company){
						$hr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['hr_training_costs']?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['hr_training_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Salarios</td>
					<?php foreach ($this->companies as $company){
						$hr_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['hr_wages_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['hr_wages_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total Recursos Humanos </a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($hr_costs[$company['id']],2, '.', ',').' €'?></th>
				    <?php }//for company ?>
				</thead>
				<!-- INICIATIVAS -->
				<thead>			
					<th></th>
					<th class='invisible categories'>
						<strong><h4>Iniciativas</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Iniciativas de Producción</td>
					<?php foreach ($this->companies as $company){				
							$in_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['initiatives_pr_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['initiatives_pr_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Iniciativas de Marketing</td>
					<?php foreach ($this->companies as $company){				
							$in_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['initiatives_mk_costs']?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['initiatives_mk_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Iniciativas de Recursos Humanos</td>
					<?php foreach ($this->companies as $company){				
							$in_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['initiatives_hr_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['initiatives_hr_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total Iniciativas</a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($in_costs[$company['id']],2, '.', ',').' €'?></th>
				    <?php }//for company ?>
				</thead>
				<!-- ESTUDIOS DE MERCADO -->
				<thead>			
					<th></th>
					<th class='invisible categories'>
						<strong><h4>Estudios de Mercado</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Coste de los Estudios contratados</td>
					<?php foreach ($this->companies as $company){				
							$research_costs[$company['id']]=$this->outcomes_costs[$company['id']]['market_researches_costs']?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['market_researches_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total Estudios de Mercado</a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($this->outcomes_costs[$company['id']]['market_researches_costs'],2, '.', ',').' €'?></th>
				    <?php }//for company ?>
				</thead>
				<!-- I+D+i -->
				<thead>			
					<th></th>
					<th class='invisible categories'>
						<strong><h4>I+D+i</h4></strong>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">Modificación de Productos</td>
					<?php foreach ($this->companies as $company){				
							$idi_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['idi_changes_costs']?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['idi_changes_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Nuevos Productos</td>
					<?php foreach ($this->companies as $company){				
							$idi_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['idi_new_costs']?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['idi_new_costs'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<a style="color:#000000">Total I+D+i</a>
					</th>
					<?php foreach ($this->companies as $company){?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><?php echo number_format($idi_costs[$company['id']],2, '.', ',').' €'?></th>
				    <?php }//for company ?>
				</thead>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>				
				<thead>
				    <th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Total Gastos</h3>
					</th>
					<?php foreach ($this->companies as $company){
						$total_costs[$company['id']]=$pr_costs[$company['id']]+
													$mk_costs[$company['id']]+
													$hr_costs[$company['id']]+
													$in_costs[$company['id']]+
													$research_costs[$company['id']]+
													$idi_costs[$company['id']]?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($total_costs[$company['id']],2, '.', ',').' €'?></strong>
								<?php /*echo ("PR.COSTS = ".$pr_costs[$company['id']]."<br/>MK. COSTS = ".$mk_costs[$company['id']]."<br/>HR.COSTS = ".
											$hr_costs[$company['id']]."<br/>IN. COSTS = ".$in_costs[$company['id']]."<br/>RES. COSTS = ".$research_costs[$company['id']]."<br/>IDI. COSTS = ".$idi_costs[$company['id']].
											"<br/>");*/?></th>
				    <?php }//for company ?>
				</thead>
				<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
				    <th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Variaci&oacute;n de Existencias</h3>
					</th>
					<?php foreach ($this->companies as $company){?>
						<?php $inventories[$company['id']]=$this->outcomes_balance_sheet[$company['id']]['stock']-$this->prev_outcomes_balance_sheet[$company['id']]['stock'];?>
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($inventories[$company['id']],2, '.', ',').' €'?></strong></th>
				<?php }//for company ?>
				</thead>
				
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>			
					<th colspan="2" class='invisible categories'>
						<h2 style="color:#A52A2A;margin-bottom:12px;margin-left:5px">EBITDA</h2>
					</th>
					<?php foreach ($this->companies as $company){
						 	$ebitda[$company['id']]=$incomes_sum[$company['id']]-($total_costs[$company['id']]-$inventories[$company['id']]) ?>
							<th nowrap style="color:#A52A2A"><strong><?php echo number_format($ebitda[$company['id']],2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<thead>
				    <th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Amortizaciones</h3>
					</th>
					<?php foreach ($this->companies as $company){ 
							$amortization[$company['id']]=$this->amortization_view[$company['id']]; ?>
					<th class="vertical_group_open" nowrap style="background-color:#FAFAD2;color:#A52A2A"><strong><?php echo number_format($amortization[$company['id']],2, '.', ',').' €'?></strong></th>
				<?php }//for company ?>
				</thead>
				<tr></tr>
					<th></th>
					<th></th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
				    	<?php }//for company ?>
				<!-- FINANCIEROS -->
				<thead>			
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Financieros</h3>
					</th>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
				</thead>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Intereses Financiación a C.P.</td>
					<?php foreach ($this->companies as $company){				
							$fi_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['fi_debt_costs_st']?>
						<td class="hor_group_even vertical_group_open" nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['fi_debt_costs_st'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Intereses Financiación a L.P.</td>
					<?php foreach ($this->companies as $company){				
							$fi_costs[$company['id']]+=$this->outcomes_costs[$company['id']]['fi_debt_costs_lt']?>
						<td class="hor_group_even vertical_group_open" nowrap><?php echo number_format($this->outcomes_costs[$company['id']]['fi_debt_costs_lt'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Intereses ganados por inversiones financieras</td>
					<?php foreach ($this->companies as $company){				
							$fi_investment_earnings[$company['id']]+=$this->outcomes_investments[$company['id']]['fi_investment_earnings']?>
						<td class="hor_group_even vertical_group_open" nowrap><?php echo number_format($this->outcomes_investments[$company['id']]['fi_investment_earnings'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">Intereses perdidos por inversiones financieras</td>
					<?php foreach ($this->companies as $company){				
							$fi_investment_losses[$company['id']]+=$this->outcomes_investments[$company['id']]['fi_investment_losses']?>
						<td class="hor_group_even vertical_group_open" nowrap><?php echo number_format($this->outcomes_investments[$company['id']]['fi_investment_losses'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>					
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Total Financieros</h3>
					</th>
					<?php foreach ($this->companies as $company){?>
						<?php //$total_fi_cost[$company['id']]=$fi_costs[$company['id']]+$fi_investment_losses[$company['id']]-$fi_investment_earnings[$company['id']];?>
						<?php $total_fi_cost[$company['id']]= $this->outcomes_costs[$company['id']]['fi_debt_costs_st']+$this->outcomes_costs[$company['id']]['fi_debt_costs_lt']+$this->outcomes_investments[$company['id']]['fi_investment_losses']-$this->outcomes_investments[$company['id']]['fi_investment_earnings'];
						if ($total_fi_cost[$company['id']]>0) { ?>
							<th class="vertical_group_open" nowrap style="background-color:#FAFAD2;color:#A52A2A;"><strong><?php echo number_format(abs($total_fi_cost[$company['id']]),2, '.', ',').' €'?></strong></th>
						<?php } else { ?>
							<th class="vertical_group_open" nowrap style="background-color:#FAFAD2;color:#000000;"><strong><?php echo number_format(abs($total_fi_cost[$company['id']]),2, '.', ',').' €'?></strong></th>
						<?php } ?>
					<?php }//for company ?>
				</thead>


				</td>
				<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>			
					<th colspan="2" class='invisible categories'>
						<h2 style="color:#A52A2A;margin-bottom:12px;margin-left:5px">EBT</h2>
					</th>
					<?php foreach ($this->companies as $company){
						 	$ebt[$company['id']]=$ebitda[$company['id']]-$amortization[$company['id']]-$total_fi_cost[$company['id']]?>
							<th nowrap style="color:#A52A2A"><strong><?php echo number_format($ebt[$company['id']],2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<tr></tr>
					<th></th>
					<th></th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
				    	<?php }//for company ?>
				<thead>
				    <th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Impuestos (25%)</h3>
					</th>
					<?php foreach ($this->companies as $company){
						if ($ebt[$company['id']]<=0) {
							$taxes[$company['id']]=0;
						} 
						else{
							$taxes[$company['id']]=($ebitda[$company['id']] - $amortization[$company['id']]-$fi_costs[$company['id']]) *0.25;
						}?>
					<th class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($taxes[$company['id']],2, '.', ',').' €'?></strong></th>
					<?php }//for company ?>
				</thead>
				<!-- BALANCE -->
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>			
					<th colspan="2" class='invisible categories'>
						<h2 style="color:#A52A2A;margin-bottom:12px;margin-left:5px">RESULTADO</h2>
					</th>
					<?php foreach ($this->companies as $company){
						 $result[$company['id']] = $ebt[$company['id']] - $taxes[$company['id']]?>
							<th nowrap style="color:#A52A2A"><strong><?php echo number_format($result[$company['id']],2, '.', ',').' €'?></strong></th>
				    <?php }//for company?>
				</thead>
			</table>
			<br/>
			<br/>
		</div>
		
		<div id="performance_outcomes" class="tab">			
				<table class="outcomes_table">
					<thead>
						<th colspan='2' class='invisible'>
							<h1 style="color:#B22222">INDICADORES</h1>
						</th>
						<?php foreach ($this->companies as $company){?>					
						<th class="vertical_group_open">
							<strong>
							<?php echo $company['name']?>
							</strong>
						</th>
					<?php } ?>
					</thead>
					<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">Ratios Anuales</h2>
						</th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
						<?php }?>
					</thead>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Margen de operación&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['margin'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Endeudamiento&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['indebtedness'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Liquidez&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
							<?php if($this->outcomes_performance[$company['id']]['liquidity']==-1.00){?>
							<td class="hor_group_even vertical_group_open"nowrap>n/a</td>
							<?php } else { ?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['liquidity'],2, '.', ',')?>&nbsp;%</td>
							<?php } ?>
						<?php } ?>
					</tr>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Solvencia&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
							<?php if($this->outcomes_performance[$company['id']]['solvency']==-1.00){?>
							<td class="hor_group_even vertical_group_open"nowrap>n/a</td>
							<?php } else { ?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['solvency'],2, '.', ',')?>&nbsp;%</td>
							<?php } ?>
						<?php } ?>
					</tr>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">(ROA) Retorno sobre activos&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['roa'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<tr>
						<?php foreach ($this->companies as $company){
							$shareholders_funds_2[$company['id']]=0;?>							
							<?php $shareholders_funds_2[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['capital'];
								  $shareholders_funds_2[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['reserves'];
								  $shareholders_funds_2[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['year_result'];?>
				   		<?php }//for company ?>					
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Rentabilidad financiera&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format(($result[$company['id']]/$shareholders_funds_2[$company['id']])*100,2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Payout Ratio&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['payout_ratio'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">Ratios Acumulados</h2>
						</th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
						<?php }?>
					</thead>
					<!--<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">(ROA) Retorno sobre activos&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['ac_roa'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>-->
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Retorno sobre el capital invertido&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['roe'],2, '.', ',')?>&nbsp;%</td>
						<?php } ?>
					</tr>
					<br/>
					<br/>
					<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">Evaluación del desempe&ntilde;o</h2>
						</th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
						<?php }?>
					</thead>
					<tr>	
						<td class="hor_group_odd categories"></td>
						<td class="hor_group_odd categories">Indicador de actividad&nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['performance_index'],2, '.', ',')?>&nbsp;</td>
						<?php } ?>
					</tr>
					<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">Valoración burs&aacute;til</h2>
						</th>
						<?php foreach ($this->companies as $company){?>
							<th></th>
						<?php }?>
					</thead>
					<tr>	
						<td class="hor_group_even categories"></td>
						<td class="hor_group_even categories">Indicador de cotización burs&aacute;til &nbsp;&nbsp;</td>
						<?php foreach ($this->companies as $company){?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_performance[$company['id']]['exchange_index'],2, '.', ',')?>&nbsp;</td>
						<?php } ?>
					</tr>
				</table>
				<br/>
				<br/>
		</div>
		
		<div id="balance_sheet_outcomes" class="tab">			
				<table class="outcomes_table">
					<thead>
						<th colspan='2' class='invisible'>
							<h1 style="color:#B22222">BALANCES</h1>
						</th>
						<?php foreach ($this->companies as $company){?>					
						<th class="vertical_group_open">
							<strong>
							<?php echo $company['name']?>
							</strong>
						</th>
					<?php } ?>
					</thead>
					<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">ACTIVO</h2>
						</th>
						<?php foreach ($this->companies as $company){
						      $asset_no_current_sum[$company['id']]=0;?>
							<th></th>
							<?php $asset_no_current_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['tied_up'];
								  $asset_no_current_sum[$company['id']]-=$this->outcomes_balance_sheet[$company['id']]['amortization'];
								  $asset_no_current_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['investment_assets'];?>
				    	<?php }//for company ?>
					</thead>
					<thead>
						<th class='invisible categories' style="background-color:#FAFAD2"></th>
						<th class='invisible categories' style="background-color:#FAFAD2">
							<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">A) Activo no corriente (I+II+III)&nbsp;&nbsp;</h3>
						</th>
						<?php foreach ($this->companies as $company){?>	
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($asset_no_current_sum[$company['id']], 2, '.', ',').' €'?></strong></th>
				   		<?php }//for company ?>
					</thead>
				<tr>	
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;I. Inmovilizado</td>
						<?php foreach ($this->companies as $company){				
							$asset_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['tied_up']?>
						<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['tied_up'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;II. Amortización de inmovilizado</td>
						<?php foreach ($this->companies as $company){
							$asset_sum[$company['id']]-=$this->outcomes_balance_sheet[$company['id']]['amortization']?>
							<td class="hor_group_odd vertical_group_open"nowrap>-<?php echo number_format($this->outcomes_balance_sheet[$company['id']]['amortization'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;III. Otras inversiones financieras</td>
						<?php foreach ($this->companies as $company){
							$asset_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['investment_assets']?>
							<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['investment_assets'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){
							$asset_current_sum[$company['id']]=0;?>
							<th></th>
							<?php $asset_current_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['stock'];
								  $asset_current_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['trade_debtors'];
								  $asset_current_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['liquid_assets'];?>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">B) Activo corriente (I+II+III)&nbsp;&nbsp;</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($asset_current_sum[$company['id']], 2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<tr>	
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;I. Existencias</td>
						<?php foreach ($this->companies as $company){
							$asset_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['stock']?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['stock'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;II. Deudores comerciales</td>
						<?php foreach ($this->companies as $company){
							$asset_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['trade_debtors']?>
							<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['trade_debtors'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;III. Tesorer&iacute;a</td>
						<?php foreach ($this->companies as $company){
							$asset_sum[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['liquid_assets']?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['liquid_assets'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Total ACTIVO (A+B)&nbsp;&nbsp;</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
						<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($asset_sum[$company['id']], 2, '.', ',').' €'?></strong></th>
				   	<?php }//for company ?>
				</thead>
				<thead>
						<th colspan='2'class='invisible categories'>
							<h2 style="color:#800000">PASIVO</h2>
						</th>
							<?php foreach ($this->companies as $company){
							$shareholders_funds[$company['id']]=0;?>
							<th></th>
							<?php $shareholders_funds[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['capital'];
								  $shareholders_funds[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['reserves'];
								  $shareholders_funds[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['year_result'];?>
				   			<?php }//for company ?>
					</thead>
					<thead>
						<th class='invisible categories' style="background-color:#FAFAD2"></th>
						<th class='invisible categories' style="background-color:#FAFAD2">
							<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">A) Patrimonio Neto (I+II+III)&nbsp;&nbsp;</h3>
						</th>
						<?php foreach ($this->companies as $company){?>				
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($shareholders_funds[$company['id']], 2, '.', ',').' €'?></strong></th>
				   		<?php }//for company ?>
					</thead>
				<tr>	
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;I. Capital</td>
						<?php foreach ($this->companies as $company){
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['capital']?>
							<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['capital'],2, '.', ',').' €'?></td>
					<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;II. Resultados de ejercicios anteriores</td>
						<?php foreach ($this->companies as $company){
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['reserves']?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['reserves'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;III. Resultado del ejercicio</td>
						<?php foreach ($this->companies as $company){
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['year_result']?>
							<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['year_result'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
						<?php foreach ($this->companies as $company){
						$liabilities_no_current[$company['id']]=0;?>
						<th></th>
						<?php $liabilities_no_current[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['long_term_debts'];
				   		}//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">B) Pasivo no corriente (I)&nbsp;&nbsp;</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($liabilities_no_current[$company['id']],2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<tr>	
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;I. Deudas a largo plazo</td>
						<?php foreach ($this->companies as $company){ 
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['long_term_debts']?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['long_term_debts'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr></tr>
					<th></th>
					<th></th>
						<?php foreach ($this->companies as $company){
						$liabilities_current[$company['id']]=0;?>
						<th></th>
						<?php $liabilities_current[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['short_term_debts'];
							  $liabilities_current[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['creditors'];
				   		}//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">C) Pasivo corriente (I+II)&nbsp;&nbsp;</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
							<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($liabilities_current[$company['id']],2, '.', ',').' €'?></strong></th>
				    <?php }//for company ?>
				</thead>
				<tr>
					<td class="hor_group_odd categories"></td>
					<td class="hor_group_odd categories">&nbsp;&nbsp;I. Deudas a corto plazo</td>
						<?php foreach ($this->companies as $company){
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['short_term_debts']?>
							<td class="hor_group_odd vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['short_term_debts'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
				<tr>
					<td class="hor_group_even categories"></td>
					<td class="hor_group_even categories">&nbsp;&nbsp;II. Acreedores comerciales</td>
						<?php foreach ($this->companies as $company){
							$liabilities_total[$company['id']]+=$this->outcomes_balance_sheet[$company['id']]['creditors']?>
							<td class="hor_group_even vertical_group_open"nowrap><?php echo number_format($this->outcomes_balance_sheet[$company['id']]['creditors'],2, '.', ',').' €'?></td>
						<?php } ?>
				</tr>
					<tr></tr>
					<th></th>
					<th></th>
					<?php foreach ($this->companies as $company){?>
							<th></th>
				    <?php }//for company ?>
				<thead>
					<th class='invisible categories' style="background-color:#FAFAD2"></th>
					<th class='invisible categories' style="background-color:#FAFAD2">
						<h3 style="background-color:#FAFAD2;color:#000000;margin-bottom:15px;margin-left:5px">Total PASIVO (A+B+C)&nbsp;&nbsp;</h3>
					</th>
					<?php foreach ($this->companies as $company){?>				
						<th  class="vertical_group_open"nowrap style="background-color:#FAFAD2;color:#000000"><strong><?php echo number_format($liabilities_total[$company['id']],2, '.', ',').' €'?></strong></th>
				   	<?php }//for company ?>
				</thead>
			</table>
			<br/>
			<br/>
		</div>

		<div id="display_outcomes" class="tab">
			</br>
			<div style="margin-left: auto; margin-right: auto; width: 500px">
				<div>
					Mostrar/Ocultar:
				</div>
				<div>
					<button id="show_hide_atmosphere">Atmósfera</button>
					<button id="show_hide_qualification">Cualificación</button>
					<button id="show_hide_deterioration">Deterioro</button>
					<button id="show_hide_development">Desarrollo productos</button>
				</div>
			</div>
			<script>
				$( "#show_hide_atmosphere" ).click(function() {
					$( ".atmosphere" ).toggle( "easeInElastic" );
				});
				$( "#show_hide_qualification" ).click(function() {
					$( ".qualification" ).toggle( "easeInElastic" );
				});
				$( "#show_hide_deterioration" ).click(function() {
					$( ".deterioration" ).toggle( "easeInElastic" );
				});
				$( "#show_hide_development" ).click(function() {
					$( ".development" ).toggle( "easeInElastic" );
				});
			</script>

			<?php   foreach ($this->companies as $company){
					$atmosphere=3*($this->atmosphere[$company['id']]);?>
				<div>	
					<div class="titulo_display_outcomes">
						<?php echo $company['name']?>
					</div>
					<div class="display_outcomes_results atmosphere">
						<div class="titulo_display_outcomes">
							Atmósfera de trabajo
						</div>
						<div style="display:block; margin-left: auto; margin-right: auto;">
							<div class="barra_resultado_texto_izquierda">
								Mala atmósfera
							</div>
							<div class="barra_resultado">
								<div id="atmosphere_bar_<?php echo $company['id']?>" class="atmosphere_bar">
								</div>
							</div>
							<div class="barra_resultado_texto_derecha">
								Buena atmósfera (<?php echo round((($atmosphere)/3), 2)?>%)
							</div>
						</div>
						<script>
							var valor_atmosfera = <?php echo $atmosphere?>;
							if (valor_atmosfera<1) {
								valor_atmosfera = 1;
							}
							
							$("#atmosphere_bar_<?php echo $company['id']?>").progressbar({
								value: valor_atmosfera,
								max: 300
							});
							
							
							if ( valor_atmosfera < 100){
								$('#atmosphere_bar_<?php echo $company['id']?> .ui-widget-header').css('background-color', '#FF0000');
							}
							if ( valor_atmosfera > 200) {
								$('#atmosphere_bar_<?php echo $company['id']?> .ui-widget-header').css('background-color', '#00FF00');
							}
							
						</script>
						<div style="clear:both"></div>	
					</div>	
					
					<div class="display_outcomes_results qualification">
						<?php $qualification=3*($this->qualification[$company['id']])?>
						<div class="titulo_display_outcomes">
							Cualificación de la plantilla
						</div>
						<div style="display:block; margin-left: auto; margin-right: auto;">
							<div class="barra_resultado_texto_izquierda">
								Baja cualificación
							</div>
							<div class="barra_resultado">
								<div id="qualification_bar_<?php echo $company['id']?>" class="qualification_bar">
								</div>
							</div>
							<div class="barra_resultado_texto_derecha">
								Alta cualificación (<?php echo round((($qualification)/3), 2)?>%)
							</div>
						</div>
						
						<script>
							var valor_cualificacion = <?php echo $qualification?>;
							if (valor_cualificacion<1) {
								valor_cualificacion = 1;
							}
							$("#qualification_bar_<?php echo $company['id']?>").progressbar({
								value: valor_cualificacion,
								max: 300
							});
							
							if (valor_cualificacion < 100){
								$('#qualification_bar_<?php echo $company['id']?> .ui-widget-header').css('background-color', '#FF0000');
							}
							if (valor_cualificacion > 200) {
								$('#qualification_bar_<?php echo $company['id']?> .ui-widget-header').css('background-color', '#00FF00');
							}
						</script>
						<div style="clear: both"></div>
					</div>
					
					<div class="display_outcomes_results deterioration">
						<?php foreach ($this->game_factories[$company['id']] as $factory){
							$deterioro=3*($this->deterioration[$company['id']]['factory_number_'.$factory['factory_number']])?>
						<div class="titulo_display_outcomes">
							Grado de deterioro Fabrica <?php echo $factory['factory_number']?><br/>
						</div>
						
						<div style="display:block; margin-left: auto; margin-right: auto;">
							<div class="barra_resultado_texto_izquierda">
								Bajo deterioro
							</div>
							<div class="barra_resultado">
								<div id="deterioration_bar_<?php echo $company['id']?>_<?php echo $factory['factory_number']?>" class="deterioration_bar">
								</div>
							</div>
							<div class="barra_resultado_texto_derecha">
								Alto deterioro (<?php echo round((($deterioro)/3), 2)?>%)
							</div>
						</div>

						<script>
							
							var valor_deterioro =  <?php echo $deterioro?>;
							if(valor_deterioro < 1){
								valor_deterioro = 1;
							}
							
						
							$("#deterioration_bar_<?php echo $company['id']?>_<?php echo $factory['factory_number']?>").progressbar({
								value: valor_deterioro,
								max: 300
							});
							
							if (valor_deterioro < 100){
								$('#deterioration_bar_<?php echo $company['id']?>_<?php echo $factory['factory_number']?> .ui-widget-header').css('background-color', '#00FF00');
							}
							if (valor_deterioro > 200) {
								$('#deterioration_bar_<?php echo $company['id']?>_<?php echo $factory['factory_number']?> .ui-widget-header').css('background-color', '#FF0000');
							}
							
						</script>
						<?php } ?>
						<div style="clear: both"></div>
					</div>
				
					<div class="display_outcomes_results development">				
						<?php 
						$tituloImpreso = false;
						foreach ($this->products as $product){
							$success=3*($this->success[$company['id']]['product_number_'.$product['product_number']]);
							if($success>0){
								if($tituloImpreso == false) {?>
									<div class="titulo_display_outcomes">Probabilidad de exito de lanzamiento de nuevos productos</div>	
									<?php $tituloImpreso = true;
								}
							?>		
								<div class="titulo_display_outcomes">
									Producto  <?php echo $product['product_number']?><br/>
								</div>
								<div style="display:block; margin-left: auto; margin-right: auto;">
									<div class="barra_resultado_texto_izquierda">
										Bajo
									</div>
									<div class="barra_resultado">
										<div id="development_success_bar_<?php echo $company['id']?>_<?php echo $product['product_number']?>" class="development_success_bar">
										</div>
									</div>
									<div class="barra_resultado_texto_derecha">
										Alto  (<?php echo round((($success)/3), 2)?>%)
									</div>
								</div>
								<script>
									var valor_development_success = <?php echo $success?>;
									if(valor_development_success < 1){
										valor_development_success = 1;
									}
									
									$("#development_success_bar_<?php echo $company['id']?>_<?php echo $product['product_number']?>").progressbar({
										value: valor_development_success,
										max: 300
									});
									
									if (valor_development_success < 100){
										$('#development_success_bar_<?php echo $company['id']?>_<?php echo $product['product_number']?> .ui-widget-header').css('background-color', '#FF0000');
									}
									if (valor_development_success > 200) {
										$('#development_success_bar_<?php echo $company['id']?>_<?php echo $product['product_number']?> .ui-widget-header').css('background-color', '#00FF00');
									}
								</script>
							<?php }?>
						<?php }?>
						<div style="clear: both"></div>
					</div>
					
					
				</div>
				<div style="clear: both"></div>
				</br>
				</br>
			<?php }?>
		</div>

		<div id="display_evolution_outcomes" class="tab">
			<script>
				function drawMarketShareGraphs() {
				// Prepare the data
				var mktSharedata = google.visualization.arrayToDataTable(<?php echo($this->array_cuotas_mercado);?>);
			  
				// Define a category picker control for the Gender column
				var marketShareProductPicker = new google.visualization.ControlWrapper({
				  'controlType': 'CategoryFilter',
				  'containerId': 'marketShareProductPickerControl',
				  'options': {
					'filterColumnLabel': 'Producto',
					'ui': {
					'labelStacking': 'vertical',
					  'allowTyping': false,
					  'allowMultiple': false,
					  'allowNone': false
					}
				  }
				});
				
				var marketShareRegionPicker = new google.visualization.ControlWrapper({
				  'controlType': 'CategoryFilter',
				  'containerId': 'marketShareRegionPickerControl',
				  'options': {
					'filterColumnLabel': 'Pais',
					'ui': {
					'labelStacking': 'vertical',
					  'allowTyping': false,
					  'allowMultiple': false,
					  'allowNone': false
					}
				  }
				});
				var marketShareChannelPicker = new google.visualization.ControlWrapper({
				  'controlType': 'CategoryFilter',
				  'containerId': 'marketShareChannelPickerControl',
				  'options': {
					'filterColumnLabel': 'Canal',
					'ui': {
					'labelStacking': 'vertical',
					  'allowTyping': false,
					  'allowMultiple': false,
					  'allowNone': false
					}
				  }
				});
			  
				// Define a Pie chart
				var marketSharePieGraph = new google.visualization.ChartWrapper({
				  'chartType': 'PieChart',
				  'containerId': 'marketSharePieGraph',
				  'options': {
					'width': 850,
					'height': 270,
					'title': 'Cuotas de mercado',
					'chartArea': {'height': "90%", 'width': "80%"},
					'pieSliceText': 'percentage',
					'tooltip': {'text': 'percentage'}
				  },
				  // Instruct the piechart to use colums 0 (Name) and 3 (Donuts Eaten)
				  // from the 'data' DataTable.
				  'view': {'columns': [3, 4]}
				});


			  
				// Create a dashboard
				new google.visualization.Dashboard(document.getElementById('marketShareDashboard')).
					// Establish bindings, declaring the both the slider and the category
					// picker will drive both charts.
					bind([marketShareProductPicker, marketShareRegionPicker, marketShareChannelPicker], [marketSharePieGraph]).
					// Draw the entire dashboard.
					draw(mktSharedata);
			  }

		  
		  </script>
			<div class="section_title">
					CUOTAS DE MERCADO 
			</div>
			</br>
			<div id="marketShareDashboard" style="width: 860px; margin-left: auto; margin-right: auto;">
				<div>Seleccione el producto, región y canal a visualizar:</br></div>
				<div style="margin-left: auto; margin-right: auto; width: 350px;">
					<div id="marketShareProductPickerControl" style="float:left"></div>
					<div id="marketShareRegionPickerControl" style="float:left"></div>
					<div id="marketShareChannelPickerControl" style="float:left"></div>
				</div>
				<div style="clear:both"></div>
				<br/>
				<div id="marketSharePieGraph"></div>
			</div>
			
			<!--CUotas de mercado sin google charts-->
			<?php //foreach ($this->products as $product){ 
					// if($this->game_product_availability['product_number_'.$product['product_number']]==1){
						// foreach ($this->regions as $region){
							// echo ('Producto:'.($product['name']).'<br /> Regi&oacute;n: '.($region['name'])); 
							// echo ($this->scriptGenerator('show_hide_links',array ('id'=>"marketShare_".$product['product_number'].$region['region_number'])));
							// echo ('<div id="marketShare_'.($product['product_number']).($region['region_number']).'" style="display:none;">');
							// echo ('<img src="/tmp/'.(md5('img_'.$this->game['id'].'_'.$this->round_number.'_'.$product['product_number'].'_'.$region['region_number'])).'.png"/>');
							// echo ('</div><br /><br />'); 
						// }				
					// }
				// }?>
		</div>
	</div>

</div>

<script>
// Set a callback to run when the Google Visualization API is loaded.
		google.setOnLoadCallback(drawMarketShareGraphs);

		
</script>