<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/jquery-ui/jquery-ui.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/forms.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/outcomes.css');?>
<?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/decision.css');?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/generalScripts.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/validators/validation.js', $type = 'text/javascript')?>
<?php echo $this->headScript()->setFile($this->baseUrl().'/javascripts/jquery.js', $type = 'text/javascript')?>
<div id='content'>
<img src="/images/people_1.gif" alt="people" width="90" height="85" style="float:right" />
		<form name="humanResources" method="post">
			<div class="fieldContainer">
				<div class="fieldHeader" id="humanResourcesCuartilFieldButton">
					Pol&iacute;tica Salarial			
				</div>
				<div id="humanResourcesCuartilField" class="fieldDiv">
					<div id="cuartilFieldDescription" class="fieldDescription" align="center">
						Determine la pol&iacute;tica de retribuci&oacute;n salarial que desea aplicar en su compa&ntilde&iacute;a.
					</div>
					<br />
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Intervalo de retribuci&oacute;n salarial:&nbsp;			
					<select name="humanResources[cuartil]" id="humanResourcesCuartil" display="block" style="margin-left:50px;">	
						<?php foreach ($this->wages as $wages){?> 
								<option value="<?php echo $wages['value']?>" <?php echo (isset($this->cuartilDecision) && $this->cuartilDecision==$wages['value'])? "selected":""?>>
								<?php echo $wages['descriptor']?>
								</option>
							<?php } ?>
					</select>
				</div>
			</div>
			<br />
			<div class="fieldContainer">
				<div class="fieldHeader" id="humanResourcesFormationFieldButton">
					Cualificaci&oacute;n de la plantilla		
				</div>
				<div id="humanResourcesFormationField" class="fieldDiv">
					<div id="formationFieldDescription" class="fieldDescription" align="center">
						Determine el perfil de cualificaci&oacute;n deseado para los trabajadores de su compa&ntilde&iacute;a.
					</div>
					<br />
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nivel de cualificaci&oacute;n:&nbsp;
						<select <?php if ($this->round_number>1){?>disabled="disabled"<?php }?> name="humanResources[formation]" id="humanResourcesFormation" display="block" style="margin-left:50px;">
						<?php foreach ($this->level as $level){?>
								<option value="<?php echo $level['value']?>" <?php echo (isset($this->formationDecision) && $this->formationDecision==$level['value'])? "selected":""?>>
								<?php echo $level['descriptor']?>
								</option>
							<?php } ?>
					</select>
				</div>
			</div>
			<br />

<!--JESUS--> 

			<div class="fieldContainer">
				<div class="fieldHeader" id="humanResourcesEmployeesFieldButton">
					Elecci&oacute;n de empleados		
				</div>
				<div id="humanResourcesEmployeeField" class="fieldDiv">
					<div id="employeeNumberSelectionField" class="fieldDescription" align="center">
						Determine el numero de empleados que desea contratar de cada categor&iacute;a:
						</div>
						<div id="employeeNumberSelectionFieldsErrors" class="fieldErrors">
						</div>
						<br />
					
						<?php foreach ($this->factories as $factory){ ?>

						&nbsp;&nbsp;&nbsp;Fabrica 	<?php echo $factory['factory_number'] ?>
							<table border="3" bordercolor="brown" align="center">
								<thead>
								<th>Categor&iacute;a</th>
								<th>N&uacute;mero</th>
								</thead>

								<?php foreach ($this->employeeCategory as $employees){ ?>	
								<tr>
								<td><?php echo $employees['name']?></td>
								<td><input type="text" name="humanResources[factories_<?php echo $factory['factory_number']?>][employee_<?php echo $employees['category_number']?>][number_employees]" class="small"
												<?php echo isset($this->employeesDecision['factory_number_'.$factory['factory_number']]['category_'.$employees['category_number']])?
													'value = "'.$this->employeesDecision['factory_number_'.$factory['factory_number']]['category_'.$employees['category_number']] 
															.'"':'value = "0"'?></input>
										 		
								</td>
								</tr>

								
								<?php } 
								 //for trademedia?>
							</table>
								<?php } ?>
					</div>
				</div>
			

			<br />

			<div class="fieldContainer">
				<div class="fieldHeader" id="humanResourcesShiftsFieldButton">
					Elecci&oacute;n de turnos		
				</div>
				<div id="humanResourcesShiftsField" class="fieldDiv">
					<div id="shiftsFieldDescription" class="fieldDescription" align="center">
						Elija el n&uacute;mero de turnos que desea implantar en sus f&aacute;bricas.
					</div>
					<br />
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Turnos:&nbsp; 
						<select name="humanResources[shifts]" id="humanResourcesShifts" display="block" style="margin-left:50px;">
						<?php foreach ($this->shifts as $shifts){?>

								<option value="<?php echo $shifts['value']?>" <?php echo (isset($this->shiftsDecision) && $this->shiftsDecision==$shifts['value'])? "selected":""?>>
								<?php echo $shifts['descriptor']?>
								</option>
							<?php } ?>
					</select>

				
				</div>
			</div>

<!--JESUS-->
	
			<br />
			<div class="buttonsDiv">
				<input class="button" type="submit" value="Guardar">
			</div>
		</form>
		<script>
			$( "#humanResourcesCuartilFieldButton" ).click(function() {
				$( "#humanResourcesCuartilField" ).toggle( "easeInElastic" );
			});
			$( "#humanResourcesFormationFieldButton" ).click(function() {
				$( "#humanResourcesFormationField" ).toggle( "easeInElastic" );
			});
			$( "#humanResourcesEmployeesFieldButton" ).click(function() {
				$( "#humanResourcesEmployeeField" ).toggle( "easeInElastic" );
			});
			$( "#humanResourcesShiftsFieldButton" ).click(function() {
				$( "#humanResourcesShiftsField" ).toggle( "easeInElastic" );
			});
		</script>
</div>